meta_product_name: "Where is the spot"
meta_title: "Where is the spot? Un spot parfait pour ton sport nautique préféré"
meta_description: "Une application pour trouvez les meilleurs spot pour vos sport nautique
                  favoris! Surf, plongée, char a voile et bien d'autre, de nombreux
                  spots vous attendent sur where is the spot!"
meta_image: "/logo/meta-image.png"
